name: "publish npm"

on: push

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4.1.2
            - name: Setup Node.js environment
              uses: actions/setup-node@v4.0.2
              with:
                  node-version: 20
                  registry-url: https://registry.npmjs.org
            - name: publish
              run: npm publish --access public
              working-directory: my-package
              env:
                  NODE_AUTH_TOKEN: ${{secrets.npm_auth_token}}
